package-name: astro-provider-ray

display-name: Kuberay

docs-url: https://github.com/astronomer/astro-provider-ray/blob/main/README.md

decorators:
  - module: ray_provider.decorators.kuberay.ray_task

operators:
  - module: ray_provider.operators.kuberay.RayClusterOperator
  - module: ray_provider.operators.kuberay.SubmitRayJob

triggers:
  - module: ray_provider.triggers.kuberay.RayJobTrigger
