kind: Cluster
name: local
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
nodes:
  - role: control-plane
    #extraPortMappings:
    #  - containerPort: 30000
    #    hostPort: 30000
    #    listenAddress: "0.0.0.0"
    #    protocol: tcp
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta3
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: host.docker.internal
