apiVersion: v1
kind: Service
metadata:
  name: ray-service
  namespace: ray
spec:
  selector:
    ray.io/cluster: raycluster-complete
    ray.io/node-type: head
  ports:
  - name: dashboard
    protocol: TCP
    port: 8265
    targetPort: 8265
  - name: client
    protocol: TCP
    port: 10001
    targetPort: 10001
  - name: gcs
    protocol: TCP
    port: 6379
    targetPort: 6379
  - name: serve
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
