name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          repository_path: '.'
          documentation_path: 'docs'
          requirements_path: 'docs/requirements.txt'
          publish: 'true'
          sphinx_build_options: ''
