name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Authorize:
    environment: ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build-and-deploy:
    needs: Authorize
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          repository_path: '.'
          documentation_path: 'docs'
          requirements_path: 'docs/requirements.txt'
          publish: 'true'
          sphinx_build_options: ''
